package de.thecoolcraft11.hideAndSeek.setting.group;

import de.thecoolcraft11.hideAndSeek.setting.spec.BooleanSettingSpec;
import de.thecoolcraft11.hideAndSeek.setting.spec.DoubleSettingSpec;
import de.thecoolcraft11.hideAndSeek.setting.spec.IntegerSettingSpec;
import de.thecoolcraft11.hideAndSeek.setting.spec.SettingSpec;
import org.bukkit.Material;

import java.util.List;

public final class SeekerItemsSettingGroup implements SettingGroup {

    @Override
    public List<SettingSpec> settings() {
        return List.of(new IntegerSettingSpec("seeker-items.grappling-hook.cooldown", 2, 0, 30,
                        "Cooldown for grappling hook in seconds", Material.CLOCK),
                new DoubleSettingSpec("seeker-items.grappling-hook.speed", 1.5, 0.3, 3.0,
                        "Base speed for grappling hook pull", Material.BLAZE_POWDER),
                new IntegerSettingSpec("seeker-items.ink-splash.cooldown", 20, 0, 60,
                        "Cooldown for ink splash in seconds", Material.CLOCK),
                new IntegerSettingSpec("seeker-items.ink-splash.radius", 25, 1, 50, "Radius of ink splash",
                        Material.COMPASS), new IntegerSettingSpec("seeker-items.ink-splash.duration", 7, 1, 30,
                        "Duration of ink blindness in seconds", Material.CLOCK),
                new IntegerSettingSpec("seeker-items.lightning-freeze.cooldown", 60, 10, 300,
                        "Cooldown for lightning freeze in seconds", Material.CLOCK),
                new IntegerSettingSpec("seeker-items.lightning-freeze.duration", 5, 1, 30,
                        "Duration of freeze in seconds", Material.CLOCK),
                new IntegerSettingSpec("seeker-items.glowing-compass.cooldown", 25, 0, 60,
                        "Cooldown for glowing compass in seconds", Material.CLOCK),
                new IntegerSettingSpec("seeker-items.glowing-compass.duration", 10, 1, 60,
                        "Duration of glow in seconds", Material.CLOCK),
                new DoubleSettingSpec("seeker-items.glowing-compass.range", 50.0, 10.0, 200.0,
                        "Range to detect nearest hider", Material.COMPASS),
                new IntegerSettingSpec("seeker-items.curse-spell.cooldown", 30, 0, 60,
                        "Cooldown for curse spell in seconds", Material.CLOCK),
                new IntegerSettingSpec("seeker-items.curse-spell.active-duration", 10, 1, 60,
                        "Duration curse spell is active on sword", Material.CLOCK),
                new IntegerSettingSpec("seeker-items.curse-spell.curse-duration", 8, 1, 60,
                        "Duration of curse on hider", Material.CLOCK),
                new IntegerSettingSpec("seeker-items.curse-spell.small-shrink-delay", 8, 1, 60,
                        "Delay before shrinking back in SMALL mode", Material.CLOCK),
                new IntegerSettingSpec("seeker-items.block-randomizer.cooldown", 45, 10, 120,
                        "Cooldown for block randomizer in seconds", Material.CLOCK),
                new IntegerSettingSpec("seeker-items.chain-pull.cooldown", 12, 0, 60,
                        "Cooldown for chain pull in seconds", Material.CLOCK),
                new DoubleSettingSpec("seeker-items.chain-pull.range", 30.0, 5.0, 100.0, "Maximum range for chain pull",
                        Material.LEAD),
                new DoubleSettingSpec("seeker-items.chain-pull.pull-power", 2.0, 0.5, 5.0, "Pull power multiplier",
                        Material.IRON_BLOCK),
                new IntegerSettingSpec("seeker-items.chain-pull.slowness-duration", 3, 1, 20,
                        "Slowness duration in seconds after pull", Material.CLOCK),
                new IntegerSettingSpec("seeker-items.proximity-sensor.cooldown", 20, 0, 60,
                        "Cooldown for proximity sensor in seconds", Material.CLOCK),
                new DoubleSettingSpec("seeker-items.proximity-sensor.range", 8.0, 1.0, 50.0,
                        "Detection range for proximity sensor", Material.SCULK_SENSOR),
                new IntegerSettingSpec("seeker-items.proximity-sensor.duration", 60, -1, 600,
                        "Duration of proximity sensor in seconds (-1 = until round ends)", Material.CLOCK),
                new DoubleSettingSpec("seeker-items.proximity-sensor.fov-angle", 90.0, 30.0, 360.0,
                        "Field of view angle for wall-mounted sensors in degrees (360 = full circle)", Material.BOW),
                new IntegerSettingSpec("seeker-items.cage-trap.cooldown", 20, 0, 60,
                        "Cooldown for cage trap in seconds", Material.CLOCK),
                new DoubleSettingSpec("seeker-items.cage-trap.range", 3.0, 1.0, 50.0, "Trigger range for cage trap",
                        Material.IRON_BARS), new IntegerSettingSpec("seeker-items.cage-trap.duration", -1, -1, 600,
                        "Duration of cage trap in seconds (-1 = until round ends)", Material.CLOCK),
                new IntegerSettingSpec("seeker-items.cage-trap.paralyze-duration", 5, 1, 60,
                        "Duration of paralyze effect when trapped in seconds", Material.CLOCK),
                new IntegerSettingSpec("seeker-items.cage-trap.setup-time", 5, 0, 60,
                        "Time in seconds the cage trap takes to set up before it can trap a player", Material.CLOCK),
                new IntegerSettingSpec("seeker-items.phantom-viewer.cooldown", 45, 0, 180,
                        "Cooldown for phantom viewer in seconds", Material.CLOCK),
                new IntegerSettingSpec("seeker-items.phantom-viewer.ray-distance", 24, 8, 64,
                        "Maximum render distance for phantom snapshot rays", Material.COMPASS),
                new BooleanSettingSpec("seeker-items.phantom-viewer.show-player-name", false,
                        "Show the target hider name when phantom snapshot is captured", Material.NAME_TAG, false),
                new IntegerSettingSpec("seeker-items.phantom-viewer.map-duration-seconds", 60, 5, 300,
                        "How long phantom snapshot maps remain in player inventory", Material.FILLED_MAP),
                new BooleanSettingSpec("seeker-items.phantom-viewer.target-random", true,
                        "Use random hider target instead of nearest hider", Material.ENDER_EYE, false),
                new BooleanSettingSpec("seeker-items.phantom-viewer.apply-to-item-map-data", false,
                        "Apply generated map data to the Phantom Viewer item instead of giving extra filled maps",
                        Material.FILLED_MAP, false),
                new BooleanSettingSpec("seeker-items.phantom-viewer.target-name-in-lore", false,
                        "Add captured target name as lore on the Phantom Viewer item", Material.NAME_TAG, false),
                new IntegerSettingSpec("seeker-items.assistant.cooldown", 120, 0, 600,
                        "Cooldown for summoning an assistant in seconds", Material.CLOCK),
                new IntegerSettingSpec("seeker-items.assistant.lifetime", 90, 5, 600,
                        "How long each assistant stays active in seconds", Material.CLOCK),
                new IntegerSettingSpec("seeker-items.assistant.max-per-seeker", 2, 1, 5,
                        "Maximum active assistants per seeker", Material.ZOMBIE_HEAD),
                new DoubleSettingSpec("seeker-items.assistant.shoot-range", 18.0, 2.0, 64.0,
                        "Range where an assistant can fire projectiles", Material.BOW),
                new IntegerSettingSpec("seeker-items.assistant.shoot-cooldown", 70, 1, 400,
                        "Ticks between assistant shots", Material.CLOCK),
                new DoubleSettingSpec("seeker-items.assistant.projectile-speed", 0.3, 0.1, 3.0,
                        "Assistant projectile speed", Material.SNOWBALL),
                new IntegerSettingSpec("seeker-items.assistant.max-hits", 2, 1, 10,
                        "Projectile hits required to destroy an assistant", Material.SHIELD),
                new IntegerSettingSpec("seeker-items.assistant.hit-direct-points", 60, 0, 500,
                        "Points awarded for a direct assistant projectile hit", Material.EMERALD),
                new IntegerSettingSpec("seeker-items.assistant.hit-near-points", 20, 0, 500,
                        "Points awarded for a near assistant projectile hit", Material.EMERALD),
                new DoubleSettingSpec("seeker-items.assistant.projectile-aim-spread-stationary", 0.06, 0.0, 0.5,
                        "Projectile spread for stationary targets (lower = more accurate)", Material.SNOWBALL),
                new DoubleSettingSpec("seeker-items.assistant.projectile-aim-spread-moving", 0.22, 0.0, 0.5,
                        "Projectile spread for moving targets (higher = less accurate)", Material.SNOWBALL),
                new DoubleSettingSpec("seeker-items.assistant.hit-direct-threshold-stationary", 1.0, 0.5, 3.0,
                        "Distance threshold for direct hits on stationary targets", Material.TARGET),
                new DoubleSettingSpec("seeker-items.assistant.hit-direct-threshold-moving", 0.35, 0.1, 1.5,
                        "Distance threshold for direct hits on moving targets", Material.TARGET),
                new DoubleSettingSpec("seeker-items.assistant.hit-moving-speed-threshold", 0.05, 0.01, 0.5,
                        "Horizontal speed threshold to consider a target as moving", Material.FEATHER),
                new DoubleSettingSpec("seeker-items.assistant.hit-moving-lucky-direct-chance", 0.1, 0.0, 1.0,
                        "Chance (0.0-1.0) for moving targets to be lucky-hit as direct despite distance",
                        Material.EMERALD),
                new DoubleSettingSpec("seeker-items.assistant.health", 6.0, 1.0, 50.0, "Assistant mob max health",
                        Material.REDSTONE), new DoubleSettingSpec("seeker-items.assistant.speed", 0.38, 0.1, 1.0,
                        "Assistant mob movement speed multiplier", Material.FEATHER),
                new DoubleSettingSpec("seeker-items.assistant.pathfind-speed-multiplier", 1.0, 0.5, 2.0,
                        "Pathfinding speed multiplier (relative to base speed)", Material.IRON_BOOTS),
                new DoubleSettingSpec("seeker-items.assistant.standoff-range", 6.0, 2.0, 20.0,
                        "Distance assistant maintains from target when shooting", Material.BOW),
                new DoubleSettingSpec("seeker-items.assistant.standoff-tolerance", 1.5, 0.5, 5.0,
                        "Tolerance range for standoff distance", Material.TARGET),
                new IntegerSettingSpec("seeker-items.assistant.sniff-interval", 15, 1, 100,
                        "Ticks between target scans", Material.CLOCK),
                new DoubleSettingSpec("seeker-items.assistant.sniff-range-front", 35.0, 5.0, 100.0,
                        "Detection range in front of assistant", Material.COMPASS),
                new DoubleSettingSpec("seeker-items.assistant.sniff-range-rear", 15.0, 2.0, 50.0,
                        "Detection range behind assistant", Material.COMPASS),
                new DoubleSettingSpec("seeker-items.assistant.sniff-hidden-multiplier", 0.5, 0.1, 1.0,
                        "Range multiplier for hidden (block-mode) targets", Material.DEEPSLATE_BRICKS),
                new DoubleSettingSpec("seeker-items.assistant.alert-range", 12.0, 2.0, 50.0,
                        "Range where assistant triggers an alert message", Material.BELL),
                new IntegerSettingSpec("seeker-items.assistant.alert-cooldown", 80, 1, 400,
                        "Ticks between alert triggers", Material.CLOCK),
                new DoubleSettingSpec("seeker-items.assistant.projectile-homing", 6.5, 0.0, 45.0,
                        "Projectile homing angle adjustment per tick in degrees", Material.ARROW),
                new DoubleSettingSpec("seeker-items.assistant.projectile-homing-range", 18.0, 5.0, 100.0,
                        "Max distance for projectile homing to be active", Material.ARROW),
                new DoubleSettingSpec("seeker-items.assistant.projectile-gravity", 0.03, 0.0, 0.1,
                        "Per-tick gravity on projectile", Material.FEATHER),
                new IntegerSettingSpec("seeker-items.assistant.projectile-lifetime", 70, 10, 400,
                        "Projectile lifetime in ticks before despawn", Material.CLOCK),
                new DoubleSettingSpec("seeker-items.assistant.projectile-aim-spread", 0.12, 0.0, 0.5,
                        "Base projectile aim spread", Material.SNOWBALL),
                new DoubleSettingSpec("seeker-items.assistant.hit-direct-threshold", 0.6, 0.1, 3.0,
                        "Distance threshold for any direct hit", Material.TARGET),
                new DoubleSettingSpec("seeker-items.assistant.hit-near-threshold", 2.5, 0.5, 10.0,
                        "Distance threshold for near hit", Material.TARGET),
                new IntegerSettingSpec("seeker-items.assistant.hit-direct-slowness-duration", 120, 1, 600,
                        "Slowness duration on direct hit (ticks)", Material.REDSTONE),
                new IntegerSettingSpec("seeker-items.assistant.hit-direct-nausea-duration", 100, 1, 600,
                        "Nausea duration on direct hit (ticks)", Material.REDSTONE),
                new IntegerSettingSpec("seeker-items.assistant.hit-near-slowness-base", 80, 1, 600,
                        "Base slowness duration on near hit (scales with distance)", Material.REDSTONE),
                new IntegerSettingSpec("seeker-items.assistant.hit-near-nausea-base", 60, 1, 600,
                        "Base nausea duration on near hit (scales with distance)", Material.REDSTONE),
                new IntegerSettingSpec("seeker-items.assistant.beam-duration", 120, 10, 400,
                        "Duration of test block beam display (ticks)", Material.CLOCK),
                new DoubleSettingSpec("seeker-items.assistant.wander-radius-phase1", 15.0, 5.0, 100.0,
                        "Wander radius phase 1 (first 20 seconds)", Material.COMPASS),
                new DoubleSettingSpec("seeker-items.assistant.wander-radius-phase2", 25.0, 5.0, 100.0,
                        "Wander radius phase 2 (20-50 seconds)", Material.COMPASS),
                new DoubleSettingSpec("seeker-items.assistant.wander-radius-phase3", 40.0, 5.0, 100.0,
                        "Wander radius phase 3 (after 50 seconds)", Material.COMPASS),
                new IntegerSettingSpec("seeker-items.sword-of-seeking.cooldown", 5, 0, 60,
                        "Cooldown for thrown seeker sword in seconds  ", Material.CLOCK),
                new IntegerSettingSpec("seeker-items.seeker-sword-throw.max-charge-seconds", 5, 1, 15,
                        "Maximum sword charge time in seconds", Material.CLOCK),
                new DoubleSettingSpec("seeker-items.seeker-sword-throw.min-speed", 0.8, 0.2, 5.0,
                        "Thrown sword speed with minimum charge", Material.TRIDENT),
                new DoubleSettingSpec("seeker-items.seeker-sword-throw.max-speed", 2.4, 0.5, 8.0,
                        "Thrown sword speed with full charge", Material.TRIDENT),
                new DoubleSettingSpec("seeker-items.seeker-sword-throw.gravity", 0.035, 0.0, 0.2,
                        "Per-tick gravity applied to the thrown sword", Material.FEATHER),
                new DoubleSettingSpec("seeker-items.seeker-sword-throw.hitbox", 0.4, 0.1, 1.5,
                        "Collision radius used for hider hit detection", Material.TARGET),
                new DoubleSettingSpec("seeker-items.seeker-sword-throw.auto-aim-strength", 0.22, 0.01, 0.6,
                        "How strongly Auto Aim bends the thrown sword toward hiders", Material.TARGET),
                new IntegerSettingSpec("seeker-items.seeker-sword-throw.max-flight-seconds", 6, 1, 30,
                        "Maximum travel time before the thrown sword despawns", Material.CLOCK),
                new IntegerSettingSpec("seeker-items.seeker-sword-throw.stuck-seconds", 12, 1, 60,
                        "How long the sword remains stuck in a block", Material.CLOCK),
                new BooleanSettingSpec("seeker-items.crowbar.enabled", true, "Enable or disable the crowbar item",
                        Material.IRON_PICKAXE, false),
                new IntegerSettingSpec("seeker-items.crowbar.cooldown", 30, 0, 60,
                        "Cooldown for crowbar block breaking in seconds", Material.CLOCK),
                new IntegerSettingSpec("seeker-items.crowbar.breaking-ticks", 100, 20, 200,
                        "Ticks it takes for the crowbar to break a block", Material.CLOCK));
    }
}
