package de.thecoolcraft11.hideAndSeek.nms;

public enum NmsCapabilities {

    BLOCK_VOXEL_SHAPE,
    MOB_PATHFINDING,
    CLIENT_GAMEMODE_SPOOFING,
    NO_CLIP_MOB,
    CLIENT_LIGHTNING_PACKET,
    PROJECTILE_ENTITY_RAYCAST,

    ANTI_CHEAT_PACKET_FILTER,
    CHANNEL_PACKET_INTERCEPTION,

    CLIENT_ENTITY_SPAWNING,
    CLIENT_ENTITY_REMOVAL,
    CLIENT_ENTITY_VISIBILITY,
    CLIENT_ENTITY_GLOWING,

    CLIENT_CAMERA_SPOOFING,
    CLIENT_CAMERA_ENTITY,

    CLIENT_FAKE_BORDER_WARNING,

    CLIENT_BLOCK_ENTITY_SPOOFING,
    CLIENT_TEST_BLOCK_BEAM,

    CUSTOM_ENTITY_GOALS,
    PER_PLAYER_DIALOG_REGISTRY,
}